# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

coverage_setting = ENV.fetch("CUCUMBER_ENABLE_COVERAGE", ENV.fetch("ENABLE_COVERAGE", "true"))

if coverage_setting == "true"
  require "simplecov"
  require "simplecov-console"

  SimpleCov.command_name "cucumber"
  SimpleCov.load_profile "rails"
  SimpleCov.formatters = SimpleCov::Formatter::MultiFormatter.new([
    SimpleCov::Formatter::HTMLFormatter,
    SimpleCov::Formatter::Console
  ])

  SimpleCov.start do
    enable_coverage :branch
    add_filter '/spec/'
    add_filter '/test/'
    add_filter '/config/'
    add_filter '/vendor/'
    add_filter '/app/mailers/'
    add_group 'Controllers', 'app/controllers'
    add_group 'Models', 'app/models'
    add_group 'Services', 'app/services'
  end

  SimpleCov.at_exit do
    result = SimpleCov.result
    covered = result.covered_lines
    total = result.total_lines
    percentage = total.zero? ? 0.0 : ((covered.to_f / total) * 100).round(2)
    puts format("\nCucumber coverage: %.2f%% covered: %d/%d\n", percentage, covered, total)
    result.format!
  end
end

require 'cucumber/rails'
require 'rspec/rails'

# Capybara defaults to CSS3 selectors rather than XPath.
# If you'd prefer to use XPath, just uncomment this line and adjust any
# selectors in your step definitions to use the XPath syntax.
# Capybara.default_selector = :xpath

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner-active_record to your Gemfile (in the :test group) if you wish to use it."
end

# You may also want to configure DatabaseCleaner to use different strategies for certain features and scenarios.
# See the DatabaseCleaner documentation for details. Example:
#
#  Before('@no-txn,@selenium,@culerity,@celerity,@javascript') do
#    # { except: [:widgets] } may not do what you expect here
#    # as Cucumber::Rails::Database.javascript_strategy overrides
#    # this setting.
#    DatabaseCleaner.strategy = :truncation
#  end
#
#  Before('not @no-txn', 'not @selenium', 'not @culerity', 'not @celerity', 'not @javascript') do
#    DatabaseCleaner.strategy = :transaction
#  end
#

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation

# Configure WebMock for API tests
require 'webmock/cucumber'
WebMock.disable_net_connect!(allow_localhost: true)

# Include RSpec mocks for Cucumber
require 'rspec/mocks'

World(RSpec::Mocks::ExampleMethods)

# Include Rack::Test for making HTTP requests in steps
require 'rack/test'
World(Rack::Test::Methods)
World(RSpec::Matchers)
World(RSpec::Rails::Matchers)

def app
  Rails.application
end

Before do
  RSpec::Mocks.setup
  ActiveJob::Base.queue_adapter = :test
  ActiveJob::Base.queue_adapter.enqueued_jobs.clear
  ActiveJob::Base.queue_adapter.performed_jobs.clear
end

After do
  begin
    RSpec::Mocks.verify
  ensure
    RSpec::Mocks.teardown
  end
end
